### ISSUE TITLE
not able to plot sankey diagram

### ISSUE THREAD

**Issue by MichaelPeibo** [hemberg-lab/scmap#14]
Hi,

When I followed the tutorial, I cannot plot sankey diagram in my firefox browser(ubuntu 16.04), I really doubt that it is due to our internet connection to google(from china).....
here is what I got
![image](https://user-images.githubusercontent.com/32219336/50049535-ba711600-0122-11e9-9d01-525bf5e1a68c.png)

Is there any alternative to change inside function to make plot works?

Thanks!

**Comment by wikiselev** [comment]
Sorry for a late reply. Could try it in a different browser?

**Comment by wikiselev** [comment]
hmm, not sure... I feel it's something on your system as opposed to `scmap` itself, but I can't reproduce. It all works ok for me in Chrome (I've just run the vignette - http://bioconductor.org/packages/release/bioc/vignettes/scmap/inst/doc/scmap.html)

**Comment by MichaelPeibo** [comment]
Hi @wikiselev 
I finally got my  plot by adding some plug for accessing google.com. It is really the internet problem.
Thanks for help!

**Comment by GabriellaNg** [comment]
I encountered the same problem TvT
![屏幕截图 2023-11-03 231018](https://github.com/hemberg-lab/scmap/assets/43919899/622afd48-e0ac-425f-a1db-6feb789aa427)
