### ISSUE TITLE
Why are the clusters of the reference dataset changed?

### ISSUE THREAD

**Issue by xbjie123** [hemberg-lab/scmap#15]
Hi,

I'd like this package very well. But here I have a little problem about the scmap-cluster.

When I did all the process for projection, the results were a little confused. The clusters are changed and the ratio of different clusters are quite dfifferent. Also, there are some unassigned cells. But as I know, the clusters would not change after the process, so I don't know what's the problem.
![default](https://user-images.githubusercontent.com/35304822/50766496-60dcb100-12b4-11e9-8d58-f694b975205f.PNG)

Thanks very much and hope to get the reply as soon as possible.

BJ

**Comment by wikiselev** [comment]
Hello, from your screenshot it looks like your clusters may be quite weak and not very well separated. That's the reason when scmap assigns all to them to State I.

**Comment by xbjie123** [comment]
Thank you very much for the quick reply.
That's true. The clusters are not very well separated. So it means this method is not proper for these clusters?
In fact, I want to observe the similarities of clusters from two different datasets. So I set one dataset as the reference (right one), the other one is the projection (left one). What I learned about this method is it can keep the identities of cells. Is it right? So I don't know why there are some unassigned cells and why the cell numbers in some clusters are decreased.

Thanks a lot.
BJ

**Comment by wikiselev** [comment]
Your result suggests that the clusters are quite weak, it does not mean that scmap is not correct, it's just telling you what happens. Unassigned cells mean that their similarity to any of the clusters is lower than a threshold (0.7 by default, can be controlled manually).

**Comment by xbjie123** [comment]
Got it.
I also did the self-projection, however, there are still some unassigned cells. So does it mean that I could get the proper threshold when the self-projection results without unassigned cells?

Best
BJ

**Comment by wikiselev** [comment]
No, the assignment result will be the same. With the lower threshold only the unassigned cells will be assigned to one of the clusters.

**Comment by xbjie123** [comment]
OK. Thank you very much for everything.
