### ISSUE TITLE
Question about using sorted cell bulk microarray data (ImmGen) as reference

### ISSUE THREAD

**Issue by atakanekiz** [hemberg-lab/scmap#19]
Hello,

Thanks for this helpful package. I have a question about mapping my scRNAseq data to the Immgen microarray data as the reference. As you probably already know, Immgen contains microarray data from hundreds of sorted immune cells from mice. I was able to get something to work, but I'd like to double-check to make sure I'm using this appropriately. Please see my code below:

## Setup scRNAseq data 

`combined` is a Seurat object containing 4 separate 10x runs aggregated. There are 15 clusters in the experiments named as numbers from 1 to 15.

```
sce <- SingleCellExperiment(assays = list(counts = as.matrix(combined@assays$RNA@counts),
                                          logcounts = as.matrix(combined@assays$RNA@data)), 
                            colData = combined@meta.data)

rowData(sce)$feature_symbol <- rownames(sce)

sce <- selectFeatures(sce, suppress_plot = FALSE)

table(rowData(sce)$scmap_features)

sce <- indexCluster(sce, cluster_col = "numeric_clusters")

head(metadata(sce)$scmap_cluster_index)

heatmap(as.matrix(metadata(sce)$scmap_cluster_index))
```

## Setup Reference dataset

I prepared Immgen microarray data by using RMA normalization for microarrays previously and saved as `immgen.rds`. In this dataset I collapsed the biological replicates (in most of the cells there are 3 replicates) to one datapoint by taking average after normalizations. This is a data frame containing normalized and log2 transformed expression values. I'm reading this data frame as the reference for scmap. `immannot` provides long names and metadata for the individual samples.

```
immgen <- readRDS("immgen.rds")
immannot <- readRDS("immannot.rds")

ref_sce <- SingleCellExperiment(assay=list(logcounts = immgen[, 2:dim(immgen)[2]]),
                                colData = immannot)

rownames(ref_sce) <-immgen$GeneName
rowData(ref_sce)$feature_symbol <- immgen$GeneName
```

## Map my own unknown data to immgen reference

```
scmapCluster_results <- scmapCluster(
  projection = ref_sce, 
  index_list = list(
  oconnell = metadata(sce)$scmap_cluster_index),
  threshold = 0     # I'm keeping this very low to see even the weekly associated cell types
)

# Prepare and informative and easy-to-explore data frame of the results
res_df <- data.frame(label = as.character(scmapCluster_results$scmap_cluster_labs),
                     similarity = as.character(scmapCluster_results$scmap_cluster_siml),
                     immgen_short = immannot$short_name,
                     immgen_type= immannot$reference_cell_type)

head(res_df)

##  label        similarity   immgen_short immgen_type
##1    11 0.871871179824524 MF.11c-11b+.Lu  Macrophage
##2     8 0.491127572913492      MF.Alv.Lu  Macrophage
##3     9 0.666813607696411     Mo.6+2+.BL    Monocyte
##4     9 0.591040179641838    Mo.6+2+.MLN    Monocyte
##5     7 0.882301399545328    Mo.6+2+.SLN    Monocyte
##6     9 0.667127563564599     Mo.6+2-.BL    Monocyte


```

Can you see anything wrong here? Is it a problem to project between scRNAseq data and bulk reference?

I also cross-posted this on Bioconductor. Feel free to close the issue if this is not the appropriate place to seek help for my question.

Best,
Atakan

**Comment by mhemberg** [comment]
Hi,

we have not tested scmap for mapping to bulk references, so I have no idea how well it will perform. My guess, however, is that it will not work very well as the gene selection step (which is critical for good results) is based on the dropout characteristic of scRNA-seq data. As this property is not a major feature of bulk data, I am concerned that the algorithm will end up making poor choices with regards to what genes to use (and consequently poor mapping). At the end of the day though the proof is in the pudding, so if you end up getting sensible results then you should go with the approach that you have outlined.
