### ISSUE TITLE
trouble installing scmap 

### ISSUE THREAD

**Issue by dat4git** [hemberg-lab/scmap#2]
I want to run scmap on some single cell datasets but ran into the following problems when installing the package. Any help would be much appreciated. Thx!

1. Installing from Bioconductor (OS X El Capitan 10.11.6 )
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
> biocLite("scmap")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.2 (2017-09-28).
Installing package(s) ‘scmap’
Warning message:
package ‘scmap’ is not available (for R version 3.4.2) 

2. Installing from github (OS X El Capitan 10.11.6 )
> devtools::install_github("hemberg-lab/scmap")
** testing if installed package can be loaded
Creating a generic function for ‘toJSON’ from package ‘jsonlite’ in package ‘googleVis’
Error: package or namespace load failed for ‘scmap’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/dat4git/Library/R/3.4/library/scmap/libs/scmap.so':
  dlopen(/Users/dat4git/Library/R/3.4/library/scmap/libs/scmap.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
  Referenced from: /Users/dat4git/Library/R/3.4/library/scmap/libs/scmap.so
  Reason: Incompatible library version: scmap.so requires version 3.5.0 or later, but libRlapack.dylib provides version 3.4.0
Error: loading failed
Execution halted

Note: Looks like the libRlapack.dylib version is causing the problem. Is there a simple way to fix this on a Mac?

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
...

3. Also tried installing on Linux .. 

> devtools::install_github("hemberg-lab/scmap")
Downloading GitHub repo hemberg-lab/scmap@master
from URL https://api.github.com/repos/hemberg-lab/scmap/zipball/master
Installing scmap
'/broad/software/free/Linux/redhat_6_x86_64/pkgs/r_3.4.0/lib64/R/bin/R'  \
  --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/15148918.1.interactive/Rtmp7l66Tu/devtools718c38bee8c4/hemberg-lab-scmap-b9cdf52'  \
  --library='/home/unix/dat4git/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package 'scmap' ...
** libs
make: Nothing to be done for `all'.
installing to /home/unix/dat4git/R/x86_64-pc-linux-gnu-library/3.4/scmap/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
Error: package or namespace load failed for 'scmap' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/unix/dat4git/R/x86_64-pc-linux-gnu-library/3.4/scmap/libs/scmap.so':
  /home/unix/dat4git/R/x86_64-pc-linux-gnu-library/3.4/scmap/libs/scmap.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/unix/dat4git/R/x86_64-pc-linux-gnu-library/3.4/scmap'
Installation failed: Command failed (1)

sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.9 (Santiago)

Matrix products: default
BLAS: /broad/software/free/Linux/redhat_6_x86_64/pkgs/r_3.4.0/lib64/R/lib/libRblas.so
LAPACK: /broad/software/free/Linux/redhat_6_x86_64/pkgs/r_3.4.0/lib64/R/lib/libRlapack.so
...

**Comment by wikiselev** [comment]
Hi, thanks for reporting this! Can you try `devtools::install_github("hemberg-lab/scmap")` again, please? And let me know what it says?

**Comment by dat4git** [comment]
Thanks! Successfully installed on OS X El Capitan 10.11.6.

**Comment by wikiselev** [comment]
Great, thanks for letting me know! I forgot to remove dynamically generated files from the `src` folder. And when you use `devtools::install_github` I suppose it will not recompile those files if you already have them. Since I have a devel version of R (3.5) you had an R version conflict on your system. Now I have removed the dynamic files from the `src` folder. Thanks again!
