### ISSUE TITLE
problem with scmapCluster

### ISSUE THREAD

**Issue by ninggongzi** [hemberg-lab/scmap#23]
Dear scmap team,
I am trying to project my scRNA-seq dataset(pyKid) against the Mus musculus kidney single-cell data (MCA). Following is my code and it report the error:
![image](https://user-images.githubusercontent.com/50333341/83935329-41202400-a7eb-11ea-8919-0765b93f07e7.png)

then I using the source code to check my data as following:
![image](https://user-images.githubusercontent.com/50333341/83935401-de7b5800-a7eb-11ea-9568-57872083830e.png)
I am confused and looking forward to your help!

Best

ninggongzi

**Comment by ninggongzi** [comment]
by the way, the pyKid was convert to an SingleCellExperiment object from an Seurat object

**Comment by wikiselev** [comment]
hi, what is the output of `traceback()` if you run it after the error?

**Comment by ninggongzi** [comment]
hello, it worked after I updated all the packages in R... 
Thanks for your reply anyway!


nonggongzi


On 6/8/2020 16:17，Vladimir Kiselev<notifications@github.com> wrote：

hi, what is the output of traceback() if you run it after the error?
