### ISSUE TITLE
broken URL in README

### ISSUE THREAD

**Issue by evanbiederstedt** [hemberg-lab/scmap#24]
Hi there @wikiselev 

I think the URL in the README directing users to the Hemberg Lab cloud service is broken---I was re-directed to all sorts of wild stuff. 

Here is the issue:
"""
A Cloud implementation of __scmap__ can be used for free without any restriction here, i.e. http://www.hemberg-lab.cloud/scmap
"""

Might be best to just remove the URL until the domain issues (or related problems) are solved. 

Thanks, Evan

**Comment by wikiselev** [comment]
Thanks Evan! I have updated the README.

**Comment by raysinensis** [comment]
Actually, the link is still there in README...still problematic

**Comment by evanbiederstedt** [comment]
Yes, the link sends users to an unsavory website now. Best to fix @wikiselev

**Comment by wikiselev** [comment]
Sorry for a late response. I believe it's fixed now.
