### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by davetang** [hemberg-lab/scmap#3]
Hi there! Thank you for the very useful package. I have a question on `selectFeatures` and whether other methods, such as using highly variable genes, will be implemented? I realise that the M3Drop preprint suggests that it out performs other feature selection methods, at least in full-transcript scRNA-seq protocols (I have UMI data by the way). If I want to implement something myself, is it simply defining a logical vector to `scmap_features` for the genes I want to use?

My problem is that the M3Drop method doesn't identify representative genes that define one of my clusters and hence even when I project the data onto itself, only half of the cells in that cluster are assigned back to that cluster. I've tried increasing the number of features/genes up to 2,000 but it doesn't improve.

**Comment by wikiselev** [comment]
Hi, thanks for your question! The short answer is: yes, if you don't like the results of M3Drop you can select features manually by defining the `scmap_features` vector in the `rowData` slot:
```
rowData(YOUR_SCE_OBJECT)$scmap_features <- YOUR_VECTOR
```

`scmap_features` values must be either `TRUE` or `FALSE` corresponding to selected and non-selected genes accordingly. This should be sufficient for your purposes, but please let me know if there are any errors.

**Comment by davetang** [comment]
Brilliant, thanks!
