### ISSUE TITLE
Error using scmapCluster

### ISSUE THREAD

**Issue by GabrielBaldissera** [hemberg-lab/scmap#35]
Hi,

I am trying to project my data to and index I have built but it yields an error and I do not know how to move on. Based on my search, this function seems to be associated to Seurat but I do not see where it would be employed since I have transformed the objects into SCE.
```

scmapCluster_results <- scmapCluster(
  projection = mir128_28H_SCE,
  index_list = list(metadata(zebrafish_Atlas_SCE)$scmap_cluster_index))
```

> Warning: The following arguments are not used: drop
> Error in CellsByIdentities(object = object, cells = cells, ...) : 
>   unused argument (drop = FALSE)
> In addition: Warning message:
> In setFeatures(projection, rownames(index)) :
>   Features ATP5MD, cct2.1, CR318588.4, EIF1B, h3f3b.1, h3f3b.1.1, h3f3b.1.2, hbae1.3.1, her15.1.1, her4.2.1, hnrnpa0l.1, krt18, mt-co3, rrm2.1, SERP1, sinhcafl.1, zgc:92066 are not present in the 'SCESet' object and therefore were not set.
> 

Here are the objects I am using:

`> mir128_28H_SCE`

> class: SingleCellExperiment 
> dim: 27310 16186 
> metadata(0):
> assays(1): ''
> rownames(27310): aaas aacs ... LOC101886033 LOC100536144
> rowData names(1): feature_symbol
> colnames(16186): MT28_AAACCCAAGAGTAACT-1 MT28_AAACCCAAGATGCTAA-1 ... WT28_TTTGTTGTCGCCTTGT-1 WT28_TTTGTTGTCTATCGGA-1
> colData names(0):
> reducedDimNames(0):
> mainExpName: NULL
> altExpNames(0):
> 

`> zebrafish_Atlas_SCE`

> class: SingleCellExperiment 
> dim: 32520 44020 
> metadata(1): scmap_cluster_index
> assays(3): counts logcounts scaledata
> rownames(32520): ptpn12 phtf2 ... LAMP5 CABZ01109058.1
> rowData names(3): feature_symbol scmap_features scmap_scores
> colnames(44020): AAACCTGAGACAGGCT-1 AAACCTGAGAGCAATT-1 ... TTTGTCATCCGGCACA-6 TTTGTCATCCTTGCCA-6
> colData names(16): orig.ident percent.mito ... nFeature_RNA ident
> reducedDimNames(3): PCA TSNE UMAP
> mainExpName: RNA
> altExpNames(0):

This is my session info in case it helps:
` sessionInfo()`

> R version 4.1.2 (2021-11-01)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server 7.9 (Maipo)
> 
> Matrix products: default
> BLAS/LAPACK: /gpfs/ycga/project/nicoli/gb587/conda_envs/r_env/lib/libopenblasp-r0.3.18.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] scmap_1.16.0                anndata_0.7.5.3             reticulate_1.23             basilisk_1.6.0              SingleCellExperiment_1.16.0
>  [6] SummarizedExperiment_1.24.0 Biobase_2.54.0              GenomicRanges_1.46.1        GenomeInfoDb_1.30.0         IRanges_2.28.0             
> [11] S4Vectors_0.32.3            BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_0.61.0          SeuratObject_4.0.4         
> [16] Seurat_4.1.0               
> 
> loaded via a namespace (and not attached):
>   [1] Rtsne_0.15             colorspace_2.0-2       deldir_1.0-6           class_7.3-20           ellipsis_0.3.2         ggridges_0.5.3        
>   [7] XVector_0.34.0         proxy_0.4-26           spatstat.data_2.1-2    farver_2.1.0           leiden_0.3.9           listenv_0.8.0         
>  [13] ggrepel_0.9.1          fansi_1.0.2            codetools_0.2-18       splines_4.1.2          polyclip_1.10-0        jsonlite_1.7.3        
>  [19] ica_1.0-2              cluster_2.1.2          png_0.1-7              uwot_0.1.11            shiny_1.7.1            sctransform_0.3.3     
>  [25] spatstat.sparse_2.1-0  compiler_4.1.2         httr_1.4.2             googleVis_0.6.11       assertthat_0.2.1       Matrix_1.4-0          
>  [31] fastmap_1.1.0          lazyeval_0.2.2         later_1.3.0            htmltools_0.5.2        tools_4.1.2            igraph_1.2.11         
>  [37] gtable_0.3.0           glue_1.6.0             GenomeInfoDbData_1.2.7 RANN_2.6.1             reshape2_1.4.4         dplyr_1.0.7           
>  [43] Rcpp_1.0.8             scattermore_0.7        vctrs_0.3.8            nlme_3.1-155           lmtest_0.9-39          stringr_1.4.0         
>  [49] globals_0.14.0         mime_0.12              miniUI_0.1.1.1         lifecycle_1.0.1        irlba_2.3.5            goftest_1.2-3         
>  [55] future_1.23.0          basilisk.utils_1.6.0   MASS_7.3-55            zlibbioc_1.40.0        zoo_1.8-9              scales_1.1.1          
>  [61] spatstat.core_2.3-2    promises_1.2.0.1       spatstat.utils_2.3-0   parallel_4.1.2         RColorBrewer_1.1-2     yaml_2.2.1            
>  [67] pbapply_1.5-0          gridExtra_2.3          ggplot2_3.3.5          rpart_4.1-15           stringi_1.7.6          randomForest_4.6-14   
>  [73] e1071_1.7-9            filelock_1.0.2         rlang_0.4.12           pkgconfig_2.0.3        bitops_1.0-7           lattice_0.20-45       
>  [79] ROCR_1.0-11            purrr_0.3.4            tensor_1.5             labeling_0.4.2         patchwork_1.1.1        htmlwidgets_1.5.4     
>  [85] cowplot_1.1.1          tidyselect_1.1.1       parallelly_1.30.0      RcppAnnoy_0.0.19       plyr_1.8.6             magrittr_2.0.1        
>  [91] R6_2.5.1               generics_0.1.1         DelayedArray_0.20.0    DBI_1.1.2              pillar_1.6.4           mgcv_1.8-38           
>  [97] fitdistrplus_1.1-6     survival_3.2-13        abind_1.4-5            RCurl_1.98-1.5         dir.expiry_1.2.0       tibble_3.1.6          
> [103] future.apply_1.8.1     crayon_1.4.2           KernSmooth_2.23-20     utf8_1.2.2             spatstat.geom_2.3-1    plotly_4.10.0         
> [109] grid_4.1.2             data.table_1.14.2      digest_0.6.29          xtable_1.8-4           tidyr_1.1.4            httpuv_1.6.5          
> [115] munsell_0.5.0          viridisLite_0.4.0 

Thanks for your help!

Best,
Gabriel

**Comment by mhemberg** [comment]
Hi Gabriel,

Thanks for your question. I am not familiar with this error and I agree with you that it could be on the Seurat side of things. I have never used scmap for Zebrafish before, so just to be sure, have you tried that it works with other data, so that it is not due to the organism/annotation somehow (seems unlikely...). Unfortunately, the person who wrote the code (Vladimir) has now left academia which means that my ability to support scmap has declined drastically as I am not familiar with the code to help much with these issues. So, sorry for the lack of support, but hopefully you can figure something out or use a more recent and better supported method instead.

Best,
Martin

**Comment by GabrielBaldissera** [comment]
Dear Martin, 

Thank you very much for your reply. I will try some other methods and I share them here if I find an answer to this problem.

Best,
Gabriel
