### ISSUE TITLE
What kind of reference dataset can be use?

### ISSUE THREAD

**Issue by FionaMoon** [hemberg-lab/scmap#36]
Hi,
I have questions about reference data. In tutorial , the reference dataset `yan` is normalized by FPKM. So , whether the input must be `FPKM` ?
What about raw counts of bulk RNA-seq data, scRNA-seq data or TPM data from TCGA ?
Thank you in advance.
Fiona

**Comment by mhemberg** [comment]
Hi Fiona,

If I remember correctly, when we tried out the method on the different pancreas datasets we did not care about the different normalization procedures and the results came out well. I believe that the algorithm should be robust in this regard so I would definitely go ahead and try it. However, if results look suspicious or if you want to be on the really safe side then you should make sure that the normalization procedure is the same for all datasets.

**Comment by FionaMoon** [comment]
Thank you for you reply!
