### ISSUE TITLE
scmap and RF/SVM comparisons

### ISSUE THREAD

**Issue by CodeInTheSkies** [hemberg-lab/scmap#4]
Hi there,

I just came across your scmap R package.  Pretty cool, and I am about to try it for my 10X data.  

While I was going through your preprint, I saw that in your comparisons, you had said that scmap slightly under-performed compared to RF and SVM classifiers.  Could you throw some more light onto this?  The thing is, scmap readily seems to offer a threshold using which I can control the "unclassified" cases.  I really like this!  If I were to build an RF classifier myself, then that might take more time.  So, I am planning to use scmap.  However, I would like to know fully well as to how scmap compares to RF classifiers, so that I can answer any such questions to the biologist whose data I am analyzing.  So, any inputs from your group would be appreciated!

By the way, when do you expect the full paper to be published?

**Comment by wikiselev** [comment]
Hi, thanks for your question. scmap didn't really underperformed SVM an RF. In the cases where their accuracy was better, the percentage of assigned cells was significantly smaller than for scmap. This means that even though SVM and RF were more accurate, this accuracy was calculated only on a small fraction of cells, all other cells were labeled as "unassigned". Please have a look at the preprint again, we describe this in the text.

scmap has already been accepted, we expect it to be published pretty soon.

**Comment by CodeInTheSkies** [comment]
Thank you very much for the response!  I like your method, and I am trying to use it for my data (10X).  

By the way, another confusion I am having is in what form should data be input to scmap?  I am using Seurat for preprocessing, and other downstream analysis, and so I have the option of either giving the completely raw UMI (10X) data, or the LogNormalized data from the object@data slot of Seurat.   Can any of these be readily given as input to scmap?  Or, should I preprocess the data in a certain way?

Would really appreciate your input as soon as possible!

Thanks.

**Comment by wikiselev** [comment]
Hey, you will need to create an object of `SingleCellExperiment` class - see our [vignette](http://bioconductor.org/packages/release/bioc/vignettes/scmap/inst/doc/scmap.html#singlecellexperiment-class) on how to do this. This can be done either using the raw counts or logged and normalised values, such as e.g. log(FPKM). Once you have the object you can run `scmap` directly on it.

**Comment by CodeInTheSkies** [comment]
Thanks!  If they are logged and normalized, then they would get assigned to
the logcounts slot directly, correct?   In that case then, does the package
automatically compute the counts in linear scale?

**Comment by wikiselev** [comment]
Hi!

> If they are logged and normalized, then they would get assigned to the logcounts slot directly, correct?
Yes

> In that case then, does the package automatically compute the counts in linear scale?
What do you mean by the linear scale?
