### ISSUE TITLE
Some general questions about scmap

### ISSUE THREAD

**Issue by CodeInTheSkies** [hemberg-lab/scmap#6]
Hi there,

The more I use your package, the more I'm liking your method!  However, to help me (and maybe others) understand the package better, I thought I will post the following general questions I had in my mind:

1) What does it mean when the similarity score is NA?

2) When I run scmapCluster on the same object as the reference (as shown in your example code), I get back a whole SingleCellExperiment object, with just the relevant slots filled with the results, correct?  But when I run it on a different object than the reference, then the output is just a list with three elements.  Correct?  This was just for my understanding, and if there are specific reasons for this, it will be great if you can please clarify!

3) What exactly is in scmap_scores column in the rowData(object) slot?

4) And finally, the order of the cells in the output is the same as the order of the cells in the input that we give in the "projection" argument of scmapCluster.  Correct?  So, essentially, to identify the cells, I can simply assign the names of the cells in the input projection object to the rownames of the output "results" object.  Correct?

I would very much appreciate the answers!

Thanks.

**Comment by wikiselev** [comment]
Hello,

Thanks, we are very glad you like scmap!

1. When similarity score is NA it means that `dropout_rate` for this gene is either 0% or 100%.
2. `scmapCluster` always returns a list with 3 items. If not, check that you using the latest version (1.1.5)
3. `scmap_scores` is the value of the top residuals of the linear fit that is produced by the `selectFeatures` function.
4. Yes, the order shouldn't change. If it does, please let me know.

Cheers,
Vlad

**Comment by CodeInTheSkies** [comment]
Thanks for your quick response and all the answers!

Can you explain a bit about dropout rate, specially, that plot using which
you do feature selection?  I have some difficulty understanding that plot.
This will also help me understand the NA values for similarity.

Thanks!
