### ISSUE TITLE
Saving the Sankey Diagram as a PDF file

### ISSUE THREAD

**Issue by CodeInTheSkies** [hemberg-lab/scmap#7]
Hello!

Just another question, this time about the Sankey diagram function of scmap.  I like this very much, as it gives a good overview of how many cells go into which clusters and such.  I see that the HTML version of the diagram that you have is also cool, as it is interactive.  However, for other purposes like presentations and publications, PDFs would be convenient.  So, is there an easy way to save the output of the "getSankey" function as a PDF file?

That will be great!  Thanks a lot!

**Comment by wikiselev** [comment]
Sankey diagrams are implemented using [googleVis](https://cran.r-project.org/web/packages/googleVis/index.html) package and it is not possible to create a pdf of the diagram due to some interactive features. However, what we did was saving an html page produced by `getSankey` as a pdf. Hope this helps.

**Comment by wikiselev** [comment]
We did print to PDF. I don't know how you can do it through R...

**Comment by iiiir** [comment]
@CodeInTheSkies you can save html file and maybe use pandoc to print to pdf?
```
p <- getSankey(
        colData(baron)$cell_type1,
        scmapCluster_results$scmap_cluster_labs[,"xin"],
        plot_height = 400
    )
print(p, "chart", file="demo.html")
```

however i do get a warning, not sure how to resolve:
![image](https://user-images.githubusercontent.com/4137873/65644540-5b8dd680-dfa9-11e9-8bd9-ed412860522a.png)
