### ISSUE TITLE
Normalisation best practices

### ISSUE THREAD

**Issue by mxposed** [hemberg-lab/scmap#9]
Hi!
I'm following the tutorial here https://github.com/hemberg-lab/tutorials/blob/master/scmap/scmap.Rmd and the vignettes here http://bioconductor.org/packages/release/bioc/manuals/scmap/man/scmap.pdf and trying to project my one 10X experiment on another 10X experiment.

I suspect the datasets in the tutorial and the `yan` dataset in vignettes are already normalised, so you can just initialise SCE as `SingleCellExperiment(assays = list(normcounts = as.matrix(yan)), colData = ann)`, directly providing `normcounts`. My datasets are just counts, and I tried to normalise them by using `normalise` function from `scmap` itself, but it is not exported for me when I do `require(scmap)`.

I would appreciate any suggestions. Perhaps, I can use Seurat's normalisation with SCE object.
Thank you

**Comment by wikiselev** [comment]
Hi,

There is no `normalise` function in `scmap`. Where did you find about it?

`scmap` does not perform any normalisation itself, but uses the `logcounts` slot by default. You can put anything in this slot but it is supposed to serve as a slot for log-transformed and normalised counts. You can perform the normalisation and log-transformation with any tool of your preference, e.g. Seurat. After that you can write you expression matrix directly to the `logcounts` slot and run `scmap`. If you don't want to bother with this you could use a simple CPM normalisation, see our functions for creating SCE objects starting from different inputs: https://github.com/hemberg-lab/scRNA.seq.datasets/blob/master/utils/create_sce.R

Hope this helps.

**Comment by mxposed** [comment]
This helps, thank you!

If you look in the table of contents of the generated pdf linked above, you'll see `normalise` function as well as several others. They can also be found inside RStudio in the help section

**Comment by wikiselev** [comment]
Ok, sorry, this functions should not be exported and visible to the user. However, I think R lists all the package functions in the manual pdf file.
